### ISSUE TITLE
Can you please develop the 3.1.x version of this mod?

### ISSUE THREAD

**Issue by skygate2012** [janukobytsch/invite-a-friend#1]
I searched all over Google and all I could find that fits my need is your mod, but my forum is the version 3.1.9, so your mod is not compatible with the newest version of phpBB. Are you considering to continue the development?
Thank you.

**Comment by janukobytsch** [comment]
This project has been deprecated for quite a while. I don't plan on maintaining it since i would have to rewrite it from scratch (the codebase is awful tbh, this was one of my first projects) and leave me with less time for new and more interesting ventures.

However, referral systems are a pretty common requirement, so there should be a few similar projects that might suite your needs, e.g. this one: https://www.phpbb.com/community/viewtopic.php?p=14380411#p14380411

If it's missing a critical feature, don't hesitate to request it on the forums - the phpBB comunity is pretty open and the devs are always looking for new ideas.

**Comment by skygate2012** [comment]
Okay then. Actually I've tried this extension, but it does not provide an invitation code feature. I'll try to request for it on the forum as you have said.
